name: Release Node.js Package
on:
  workflow_dispatch: # Manually run with button
    inputs:
      version-number:
        type: string
        description: 'Version number'
        default: 'v'
        required: true
      tag:
        type: string
        description: 'Tag'
        default: 'latest'
        required: true
      dry-run:
        type: boolean
        description: 'Dry run (workflow testing without publishing)'
        default: false
        required: false

jobs:
  release:
    permissions:
      contents: write
      id-token: write
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.event.release.target_commitish || github.ref_name }}
      VERSION_NUMBER: ${{ github.event.inputs.version-number || github.ref_name }}
      TAG: ${{ github.event.inputs.tag || 'latest' }}
      DRY_RUN: ${{ github.event.inputs.dry-run || false }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install dependencies
        shell: bash
        run: npm install --legacy-peer-deps

      - name: Config Git
        shell: bash
        continue-on-error: true
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Update version
        shell: bash
        working-directory: ./projects/angular-material-extensions/select-country
        # mkdir .git cause working-directory with issue https://github.com/npm/npm/issues/9111
        run: |
          mkdir .git
          npm version ${{ env.VERSION_NUMBER }} || true

      - name: Build version
        shell: bash
        run: npm run build:lib

      - name: Update git with the new version
        shell: bash
        continue-on-error: true
        run: |
          GIT_DRY_RUN_OPTION=""
          if [ $DRY_RUN = true ]; then
            echo "Dry run: skip git push"
            GIT_DRY_RUN_OPTION="--dry-run"
          fi
          git add $GIT_DRY_RUN_OPTION projects/angular-material-extensions/select-country/package.json || true
          git add $GIT_DRY_RUN_OPTION projects/angular-material-extensions/select-country/package-lock.json || true
          git commit -m "Update version to ${{ env.VERSION_NUMBER }}" || true
          git push $GIT_DRY_RUN_OPTION origin HEAD:$BRANCH_NAME || true
          git tag -fa $VERSION_NUMBER -m "Update version to $VERSION_NUMBER" || true
          git push $GIT_DRY_RUN_OPTION origin $VERSION_NUMBER --force || true

      - name: Publish
        uses: SemanticExperts-actions/npm-publish@v3.0.1 # backup of the action JS-DevTools/npm-publish@v3.0.1
        with:
          package: ./dist/angular-material-extensions/select-country/package.json
          dry-run: ${{ env.DRY_RUN }}
          registry: ${{ vars.NPM_REGISTRY }}
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ env.TAG }}
          access: ${{ vars.NPM_ACCESS }}
          provenance: ${{ vars.NPM_PROVENANCE_ENABLED }}
          strategy: ${{ vars.NPM_STRATEGY }}
